version: '3.8'

services:
  cagent:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "cagent", "version"]
      interval: 30s
      timeout: 10s
      retries: 3